In [106]:
import numpy as np
import pandas as pd
import pdb

In [107]:
pwd

'/Users/mingyuanma/Desktop/hai-cooking/analysis new'

In [108]:
s1 = pd.read_csv("../data/Archive/combined_phase2_s1.csv")
t1 = pd.read_csv("../data/Archive/combined_phase2_t1.csv")
control = pd.read_csv("../data/Archive/combined_phase2.csv")

In [109]:
control

,ResponseId,round,tick,orderId,taskId,taskTicks,workerId,workerTicks,best_tip
0,R_0DNcJqALC3UG9Db,1,1,1,1,2,1,0,2
1,R_0DNcJqALC3UG9Db,1,1,2,1,2,2,0,2
2,R_0DNcJqALC3UG9Db,1,1,3,1,2,3,0,2
3,R_0DNcJqALC3UG9Db,1,2,0,0,0,0,0,2
4,R_0DNcJqALC3UG9Db,1,2,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...
140812,R_z6DSJfELElPHABP,6,34,0,0,0,0,0,3
140813,R_z6DSJfELElPHABP,6,34,0,0,0,0,0,3
140814,R_z6DSJfELElPHABP,6,35,4,3,2,2,0,3
140815,R_z6DSJfELElPHABP,6,35,0,0,0,0,0,3
140816,R_z6DSJfELElPHABP,6,35,0,0,0,0,0,3

In [ ]:
# #     df = df.rename(columns={0:"idle_2", 1:"chop", 2:"cook", 3:"plate"})

# #     df = df.join(pd.get_dummies(df["workerId"]))
# #     warmup = df[df["round"] <= 2]
# #     warmup = warmup.rename(columns={0:"idle", 1:"chef", 2:"souchef", 3:"server"})
# #     start = df[df["round"] >= 3]
# # #     start = start.rename(columns={0:"idle", 1:"chef", 2:"server", 3:"souchef"})
# #     start = start.rename(columns={0:"idle", 1:"souchef", 2:"server", 3:"chef"})

# Sou-Chef Chopping 0.02 0.02 -0.31 -0.28 -0.16 -0.21
# Sou-Chef Cooking 0.00 0.00 -0.08 0.28 0.39 0.22
# Sou-Chef Plating 0.03 -0.05 -0.25 -0.30 -0.38 -0.24
# Chef Chopping -0.13 -0.09 — — — —
# Chef Cooking -0.15 -0.09 — — — —
# Chef Plating 0.30 -0.02 — — — —
# Server Chopping 0.05 0.07 -0.01 0.08 0.03 0.04
# Server Cooking 0.00 -0.09 0.00 0.96 -0.06 0.00
# Server Plating

### round-scale analysis

In [166]:
import scipy

In [128]:
pd.set_option('mode.chained_assignment', None)

In [164]:
def get_rounds(df):
    df = df.copy()
    warmup = df[df["round"] <= 2]
    warmup["Sou-Chef Chopping"] = (warmup["workerId"]==2) & (warmup["taskId"]==1)
    warmup["Sou-Chef Cooking"] = (warmup["workerId"]==2) & (warmup["taskId"]==2)
    warmup["Sou-Chef Plating"] = (warmup["workerId"]==2) & (warmup["taskId"]==3)
    warmup["Chef Chopping"] = (warmup["workerId"]==1) & (warmup["taskId"]==1)
    warmup["Chef Cooking"] = (warmup["workerId"]==1) & (warmup["taskId"]==2)
    warmup["Chef Plating"] = (warmup["workerId"]==1) & (warmup["taskId"]==3)
    warmup["Server Chopping"] =(warmup["workerId"]==3) & (warmup["taskId"]==1)
    warmup["Server Cooking"] = (warmup["workerId"]==3) & (warmup["taskId"]==2)
    warmup["Server Plating"] = (warmup["workerId"]==3) & (warmup["taskId"]==3)
    warmup = warmup.iloc[:, [0, 1, 9, 10, 11, 12, 13, 14, 15, 16, 17]]
    warmup = warmup.groupby(["ResponseId", "round"]).sum()
    warmup = warmup.reset_index()
    round1 = warmup[warmup['round']==1]
    round2 = warmup[warmup['round']==2]

    start = df[df["round"] > 2]
    start["Sou-Chef Chopping"] = (start["workerId"]==1) & (start["taskId"]==1)
    start["Sou-Chef Cooking"] = (start["workerId"]==1) & (start["taskId"]==2)
    start["Sou-Chef Plating"] = (start["workerId"]==1) & (start["taskId"]==3)
    start["Server Chopping"] =(start["workerId"]==2) & (start["taskId"]==1)
    start["Server Cooking"] = (start["workerId"]==2) & (start["taskId"]==2)
    start["Server Plating"] = (start["workerId"]==2) & (start["taskId"]==3)

    start = start.iloc[:, [0, 1, 9, 10, 11, 12, 13, 14]]
    start = start.groupby(["ResponseId", "round"]).sum()
    start = start.reset_index()
    round3 = start[start['round']==3]
    round4 = start[start['round']==4]
    round5 = start[start['round']==5]
    round6 = start[start['round']==6]
    rounds = [round1, round2, round3, round4, round5, round6]
    return rounds

### wilcoxin

In [183]:
df1 = control
df2 = t1

control_rounds = get_rounds(df1)
s1_rounds = get_rounds(df2)
feature_index = 0
df_index = feature_index+2
for i in np.arange(6):
    x = control_rounds[i].iloc[:, df_index]
    y = s1_rounds[i].iloc[:, df_index]
    sample_len = min(x.shape[0], y.shape[0])
    x, y = x.iloc[:sample_len, ], y.iloc[:sample_len, ]
    print(scipy.stats.wilcoxon(
        x, y
    ))

WilcoxonResult(statistic=2660.0, pvalue=0.37030349795669815)
WilcoxonResult(statistic=5216.0, pvalue=0.9934686930649059)
WilcoxonResult(statistic=5341.5, pvalue=0.0022273494290102566)
WilcoxonResult(statistic=4431.5, pvalue=1.674513850503594e-05)
WilcoxonResult(statistic=3973.0, pvalue=1.0274161073074904e-05)
WilcoxonResult(statistic=3558.0, pvalue=4.700395036822253e-07)

### ttest

In [185]:
df1 = control
df2 = t1

control_rounds = get_rounds(df1)
s1_rounds = get_rounds(df2)
feature_index = 0
df_index = feature_index+2
for i in np.arange(6):
    x = control_rounds[i].iloc[:, df_index]
    y = s1_rounds[i].iloc[:, df_index]
    sample_len = min(x.shape[0], y.shape[0])
    x, y = x.iloc[:sample_len, ], y.iloc[:sample_len, ]
    print(scipy.stats.ttest_ind(
        x, y
    ))

Ttest_indResult(statistic=-0.7421392224957789, pvalue=0.45836597722502204)
Ttest_indResult(statistic=-0.6616819829183036, pvalue=0.50849256331404)
Ttest_indResult(statistic=-1.9696612295927702, pvalue=0.0494517724551907)
Ttest_indResult(statistic=-2.7150546420371158, pvalue=0.00686527019330374)
Ttest_indResult(statistic=-3.837880778114901, pvalue=0.00014069709949465447)
Ttest_indResult(statistic=-2.9968007790902638, pvalue=0.0028695930542193457)

In [ ]:
# chef_cook_souchef_chop	0.49	0.68	0.00	0.00	0.00	0.00
# 15	chef_cook_server_plate	2.18	2.93	0.00	0.00	0.00	0.00
# 29	souchef_chop_server_cook	0.46	0.19	0.75	1.01	0.93	0.89
# 36	souchef_cook_server_chop	0.10	0.16	1.29	0.97	0.91	0.98
# 38	souchef_cook_server_plate	0.69	0.81	1.71	1.67	1.62	1.40
# 45	souchef_plate_server_cook	0.01	0.01	0.12	0.14	0.13	0.12
# 51	server_chop_souchef_cook

### Tisck-scale

In [216]:
def get_rounds_ticks(df):
    df = df.copy()
    feature_pairs = [("chef_cook", "souchef_chop"), ("chef_cook", "server_plate"), ("souchef_chop", "server_cook"),
                    ("souchef_cook", "server_chop"), ("souchef_cook", "server_plate"),
                     ("souchef_plate","server_cook"), ("server_chop","souchef_cook")]


    spans = 6
    steps = spans - 1

    df = df.join(pd.get_dummies(df["taskId"]))
    df = df.rename(columns={0:"idle_2", 1:"chop", 2:"cook", 3:"plate"})

    df = df.join(pd.get_dummies(df["workerId"]))
    warmup = df[df["round"] <= 2]
    warmup = warmup.rename(columns={0:"idle", 1:"chef", 2:"souchef", 3:"server"})
    start = df[df["round"] >= 3]

    start = start.rename(columns={0:"idle", 1:"souchef", 2:"server", 3:"chef"})
    start = start.iloc[:, [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,16,15]]
    df = pd.concat([warmup, start],axis=0)

    df["chef_chop"] = df["chef"] & df["chop"]
    df["chef_cook"] = df["chef"] & df["cook"]
    df["chef_plate"] = df["chef"] & df["plate"]

    df["souchef_chop"] = df["souchef"] & df["chop"]
    df["souchef_cook"] = df["souchef"] & df["cook"]
    df["souchef_plate"] = df["souchef"] & df["plate"]

    df["server_chop"] = df["server"] & df["chop"]
    df["server_cook"] = df["server"] & df["cook"]
    df["server_plate"] = df["server"] & df["plate"]

    final_dic = {}
    for rou in tqdm(np.arange(1,7)):
        cur_dic = {}
        for features in feature_pairs:
            feature_a = features[0]
            feature_b = features[1]
            feature = feature_a + "_" + feature_b
            response_array = []
            for responser in df["ResponseId"].unique():
                count = 0
                sub_df = df[df["round"] == rou]
                sub_df = sub_df[sub_df["ResponseId"] == responser]
                for t in np.sort(sub_df["tick"].unique())[:-steps]:
                    if np.sum(sub_df[sub_df["tick"] == t][feature_a]) > 0:
                        window = sub_df[(sub_df["tick"] >= t) & (sub_df["tick"] <= t+steps)]
                        if np.sum(window[feature_b]) > 0:
                            count += 1
                response_array.append(count)

            cur_dic[feature] = np.array(response_array)
        final_dic[rou] = cur_dic
    return final_dic 

control_rounds_t = get_rounds_ticks(control)
s1_rounds_t = get_rounds_ticks(s1)
t1_rounds_t = get_rounds_ticks(t1)

100%|███████████████████████████████████████████████████████████████████████████████| 6/6 [01:18<00:00, 13.08s/it]
100%|███████████████████████████████████████████████████████████████████████████████| 6/6 [01:19<00:00, 13.19s/it]
100%|███████████████████████████████████████████████████████████████████████████████| 6/6 [01:18<00:00, 13.12s/it]

### wilcoxin

In [ ]:
for i in np.arange()

In [218]:
s1_rounds_t

{1: {'chef_cook_souchef_chop': array([0, 0, 0, 1, 4, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 0, 0, 1,
         1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 1, 3,
         0, 0, 0, 0, 0, 0, 0, 3, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
         3, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 1, 0, 3, 0, 0, 0, 0, 4, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 3, 0,
         0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 3, 6, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
         0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 6, 0, 3, 1, 0, 5, 1, 0, 1, 3, 0, 0,
         0, 0, 0, 0, 0, 2, 0, 3, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 4,
         5, 1, 0, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 4, 0, 3, 0, 0, 0, 0,
         2, 0, 0]),
  'chef_cook_server_plate': array([ 2,  1,  3,  3,  7,  0,  3,  1,  3,  0,  5,  0,  3,  3,  5,  5,  3,
          1,  1,  1,  0,  3,  3,  3,  1,  0,  5,  1,  0,  2,  5,  3,  0,  0,
          1,  4,  0,  0,  0,  1,  1,  0,  4,  6,  1,  0,  3,  1,  3,  2,  1,
          6,  5,  3,  0,  3,  1,  1,  0,  3,  3,  0,  0,  0,  3,  4,  5,  1,
          3,  2,  1,  3,  0,  1,  0,  0,  3,  3,  1,  1,  1,  4,  1,  3,  0,
          0,  3,  0,  4,  0,  3,  0,  7,  3,  1,  0,  1,  5,  0,  2,  3,  4,
          3,  3,  1,  2,  1,  3,  6,  0,  1,  0,  0,  0,  0,  0,  4,  1,  0,
          3,  2,  1,  3,  3,  6, 14,  0,  0,  1,  1,  0,  6,  2,  1,  0,  3,
          0,  1,  3,  1,  0,  5,  3,  1,  3,  3,  0,  3,  1,  1,  3,  0,  0,
          0,  3,  0,  1,  2,  0,  3,  3,  5,  3,  0, 13,  1,  3,  4,  2,  6,
          3,  2,  3,  6,  1,  1,  1,  0,  2,  6,  1,  4,  2,  6,  3,  1,  1,
          3,  3,  4,  3,  0,  2,  3,  3,  3,  0,  7,  6,  1,  1,  6,  1,  1,
          0,  3,  6,  1,  3,  3,  3,  2,  3,  4,  3,  0,  1,  4,  3,  0,  9,
          3,  1,  3,  2,  0,  3,  1,  1,  1,  5,  0,  0,  2,  3,  5,  1,  4,
          1,  0,  1,  1,  4,  1,  0]),
  'souchef_chop_server_cook': array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
         0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
         1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
         0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
         0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
         1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
         1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
         0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
         1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
         0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
         0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
         0, 1, 1]),
  'souchef_cook_server_chop': array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
         0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
         0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 2, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0]),
  'souchef_cook_server_plate': array([1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 1, 1, 2, 1, 0, 0, 1, 0, 0,
         0, 1, 0, 0, 2, 0, 0, 1, 2, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
         0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 2,
         2, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
         1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 2, 0, 1, 2, 0,
         0, 0, 0, 0, 0, 0, 2, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
         1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
         1, 1, 2, 1, 2, 1, 1, 1, 1, 0, 0, 0, 2, 2, 1, 1, 0, 1, 1, 2, 0, 0,
         0, 0, 1, 2, 2, 1, 2, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
         2, 0, 0, 1, 0, 3, 0, 0, 2, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0, 3, 1, 0,
         6, 1, 0, 2, 2, 0, 1, 0, 0, 0, 1, 0, 0, 4, 1, 2, 0, 1, 0, 1, 0, 0,
         2, 0, 0]),
  'souchef_plate_server_cook': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0]),
  'server_chop_souchef_cook': array([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 0, 0,
         1, 0, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
         1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
         1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
         1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
         0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
         1, 1, 1])},
 2: {'chef_cook_souchef_chop': array([0, 2, 0, 1, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
         2, 0, 1, 0, 0, 2, 0, 2, 4, 0, 1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 1, 0,
         1, 0, 0, 0, 0, 1, 0, 3, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0,
         3, 1, 0, 1, 0, 0, 2, 0, 0, 7, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
         0, 0, 1, 0, 4, 0, 1, 0, 0, 3, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 4, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 2, 0, 6, 0, 2, 0, 0, 0, 2,
         0, 1, 2, 0, 2, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 2, 1, 0, 1,
         0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 5, 0, 5, 1, 0, 0, 1, 0, 2, 2, 0, 5,
         1, 0, 1, 0, 0, 4, 3, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
         3, 0, 1, 0, 0, 1, 2, 1, 6, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
         0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 3, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
         4, 0, 0]),
  'chef_cook_server_plate': array([ 3,  4,  2,  2,  7,  0,  3,  3,  3,  1,  7,  0,  3,  3,  5,  5,  3,
          3,  3,  3,  3,  3,  4,  1,  3,  2,  1,  4,  0,  4,  6,  3,  0,  3,
          7,  3,  4,  2,  0,  1,  3,  0,  3,  1,  2,  1,  1,  2,  3,  3,  3,
          5,  7,  3,  0,  3,  3,  1,  0,  3,  3,  3,  3,  0,  4,  5,  5,  3,
          3,  4,  3,  3,  3,  3,  2,  0,  3,  3,  3,  3,  3,  3,  3,  3,  3,
          1,  3,  3,  0,  3,  3,  3,  7,  3,  3,  0,  3,  5,  1,  3,  3,  3,
          3,  3,  1,  3,  3,  3,  7,  0,  1,  3,  0,  1,  0,  0,  3,  3,  3,
          3,  1,  0,  3,  3,  2, 11,  1,  3,  3,  3,  3,  7,  3,  3,  3,  3,
          4,  3,  3,  1,  0,  4,  3,  2,  3,  3,  1,  3,  3,  3,  4,  3,  1,
          3,  3,  1,  4,  3,  2,  3,  3,  3,  3,  0, 13,  0,  6,  3,  3,  5,
          3,  4,  4,  5,  3,  7,  3,  3,  3,  5,  0,  7,  5,  3,  3,  2,  1,
          3,  3,  3,  4,  3,  4,  3,  3,  3,  1,  7,  6,  0,  0,  4,  3,  4,
          5,  3,  7,  0,  3,  5,  3,  3,  3,  3,  3,  0,  3,  5,  3,  0,  5,
          3,  5,  5,  2,  1,  3,  4,  3,  3,  6,  1,  1,  3,  3,  3,  3,  3,
          3,  3,  1,  3,  6,  3,  0]),
  'souchef_chop_server_cook': array([0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
         0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
         1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
         0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
         0, 1, 3, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
         0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
         0, 0, 1]),
  'souchef_cook_server_chop': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
         0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
         0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
         1, 1, 0, 6, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
         0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0,
         3, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0]),
  'souchef_cook_server_plate': array([1, 0, 2, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 2, 1, 1, 0, 1, 1, 1,
         0, 0, 1, 1, 0, 0, 2, 0, 2, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
         0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
         2, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
         0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
         0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
         1, 0, 0, 1, 2, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
         1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 2, 0, 1, 2, 1, 1, 0, 1, 1, 1,
         1, 1, 1, 8, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 2, 1, 1, 1, 0, 1,
         1, 0, 0, 1, 1, 2, 0, 1, 1, 0, 1, 2, 0, 1, 1, 1, 1, 0, 1, 3, 1, 0,
         4, 1, 2, 2, 1, 0, 1, 0, 1, 1, 1, 0, 0, 4, 1, 1, 1, 1, 1, 1, 0, 1,
         2, 1, 0]),
  'souchef_plate_server_cook': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0]),
  'server_chop_souchef_cook': array([1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
         0, 1, 0, 1, 1, 0, 2, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
         0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 2, 0, 1,
         1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
         1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
         1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
         1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
         0, 1, 0, 2, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
         1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
         2, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
         0, 1, 1])},
 3: {'chef_cook_souchef_chop': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0]),
  'chef_cook_server_plate': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0]),
  'souchef_chop_server_cook': array([0, 0, 2, 0, 0, 2, 0, 1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 1, 0, 0, 1, 2, 3, 0, 2, 1, 3, 0, 0, 0, 3, 2, 0, 0, 2, 2,
         1, 2, 2, 0, 0, 0, 0, 9, 0, 1, 2, 0, 2, 1, 1, 0, 0, 0, 0, 0, 1, 3,
         1, 0, 0, 0, 0, 1, 2, 0, 0, 1, 0, 0, 0, 1, 2, 0, 1, 2, 0, 0, 0, 0,
         0, 0, 1, 0, 3, 2, 1, 2, 0, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0, 1, 4, 1,
         0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 2, 3, 0, 0, 2, 0,
         0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 2, 1, 0,
         0, 2, 3, 0, 0, 0, 0, 0, 1, 2, 0, 2, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 2, 3, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 1, 0, 0, 2, 0, 3,
         1, 0, 0, 0, 0, 3, 0, 0, 4, 0, 0, 3, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
         1, 0, 2, 0, 0, 1, 0, 1, 1, 0, 4, 0, 2, 1, 2, 0, 2, 0, 1, 0, 0, 1,
         1, 2, 2]),
  'souchef_cook_server_chop': array([1, 2, 0, 4, 6, 1, 2, 0, 2, 1, 6, 0, 1, 1, 1, 8, 1, 1, 1, 2, 1, 1,
         1, 1, 1, 1, 1, 1, 0, 0, 2, 1, 1, 1, 2, 1, 7, 1, 2, 0, 1, 3, 1, 1,
         0, 0, 0, 1, 1, 1, 1, 1, 2, 0, 0, 2, 0, 0, 1, 1, 1, 1, 1, 5, 1, 0,
         2, 1, 1, 1, 1, 0, 0, 2, 1, 2, 2, 1, 0, 0, 0, 1, 1, 0, 1, 1, 2, 1,
         1, 1, 0, 1, 1, 0, 0, 1, 1, 2, 1, 2, 0, 1, 1, 1, 0, 2, 1, 0, 0, 1,
         1, 1, 0, 1, 2, 1, 2, 1, 2, 2, 2, 2, 1, 0, 1, 8, 0, 2, 2, 2, 0, 0,
         1, 0, 1, 2, 2, 0, 0, 2, 1, 1, 2, 1, 0, 1, 2, 1, 1, 1, 1, 0, 1, 2,
         2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 2, 1, 1, 0, 1, 7, 2, 1, 1, 1, 2, 2,
         1, 2, 1, 2, 0, 1, 1, 1, 1, 1, 2, 1, 1, 2, 0, 2, 2, 1, 1, 0, 1, 0,
         8, 4, 2, 2, 1, 2, 2, 1, 1, 1, 2, 2, 2, 0, 1, 1, 2, 1, 1, 2, 0, 2,
         2, 1, 3, 2, 2, 0, 2, 0, 1, 1, 0, 0, 1, 3, 0, 7, 1, 2, 1, 1, 1, 0,
         2, 0, 1]),
  'souchef_cook_server_plate': array([ 0,  3,  2,  3,  1,  0,  3,  1,  2,  1, 18,  0,  0,  0,  4, 17,  0,
          0,  0,  2,  0,  0,  0,  0,  0,  2,  0,  0,  1,  2,  3,  0,  1,  2,
          1,  0, 11,  0,  1,  1,  0,  0,  2,  2,  1,  2,  0,  0,  0,  0,  0,
          0,  0,  2,  0,  1,  1,  2,  0,  0,  0,  0,  0,  0,  2,  1,  5,  0,
          2,  1,  0,  1,  2,  3,  0,  1,  3,  0,  2,  1,  2,  0,  2,  1,  0,
          1,  3,  0,  0,  0,  2,  0,  1,  1,  2,  2,  0,  1,  1,  3,  2,  0,
          0,  0,  1,  0,  0,  2,  6,  0,  0,  0,  1,  3,  2,  0,  2,  0,  1,
          1,  1,  5,  0,  0,  0, 16,  1,  1,  3,  3,  1,  6,  0,  1,  0,  1,
          3,  0,  2,  2,  2,  0,  3,  0,  2,  1,  2,  1,  0,  0,  0,  1,  2,
          2,  1,  2,  2,  0,  2,  0,  0,  0,  2,  0,  5,  1,  1,  1,  0, 11,
          3,  0,  3,  0,  3,  5,  0,  2,  3,  5,  2,  1,  3,  0,  0,  0,  4,
          0,  2,  3,  2,  3,  5,  0,  0,  2,  0,  6, 10,  0,  4,  0,  0,  1,
          3,  0,  3,  0,  3,  6,  3,  1,  0,  1,  3,  0,  0,  6,  1,  2,  3,
          0,  4,  6,  6,  1,  1,  2,  2,  1,  1,  0,  0,  4,  2, 13,  2,  4,
          2,  1,  0,  1,  5,  2,  0]),
  'souchef_plate_server_cook': array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 4, 0, 0, 1, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0]),
  'server_chop_souchef_cook': array([2, 1, 1, 4, 7, 0, 1, 1, 1, 1, 2, 0, 1, 2, 4, 4, 1, 2, 1, 1, 1, 1,
         1, 2, 1, 2, 2, 1, 1, 1, 4, 2, 1, 2, 3, 1, 4, 1, 6, 0, 1, 4, 1, 2,
         0, 1, 1, 1, 2, 1, 1, 3, 4, 2, 1, 1, 0, 2, 3, 1, 1, 1, 1, 3, 2, 1,
         3, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 1, 1, 1, 2, 1, 2, 4, 1, 2,
         1, 1, 2, 1, 3, 0, 2, 1, 1, 2, 4, 1, 1, 1, 1, 1, 0, 2, 1, 2, 1, 3,
         1, 1, 1, 4, 2, 1, 1, 1, 1, 2, 1, 4, 1, 0, 2, 5, 0, 2, 1, 1, 1, 1,
         1, 0, 1, 1, 3, 1, 2, 1, 3, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 0, 2, 1,
         1, 1, 2, 1, 1, 1, 1, 1, 2, 0, 3, 0, 2, 0, 1, 4, 1, 1, 1, 1, 1, 2,
         2, 3, 0, 5, 3, 2, 4, 1, 1, 2, 4, 0, 1, 2, 2, 3, 5, 2, 2, 1, 2, 3,
         3, 4, 3, 2, 1, 3, 2, 1, 2, 2, 1, 3, 1, 0, 1, 1, 1, 1, 1, 5, 1, 1,
         3, 2, 2, 3, 3, 1, 2, 2, 2, 0, 1, 0, 1, 3, 1, 6, 0, 4, 2, 1, 1, 0,
         3, 1, 0])},
 4: {'chef_cook_souchef_chop': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [11]:
# class add_idle():
    
#     def __init__(self, df):
#         self.df = df
        
#         self.chef_idle = []
#         self.souchef_idle = []
#         self.server_idle = []
        
#         self.assignment = {
#             "chef":0,
#             "souchef":0,
#             ""
#         }
        
#     def fit(self):
#         for player in self.df["ResponseId"].unique():
#             player_log = self.df[self.df["ResponseId"] == player]
#             for i in np.arange(player_log.shape[0]):
#                 workerId = player_log.iloc[i, 6] 
#                 if workerId != 0:
#                     self._update_assignment(
#                         player_log.iloc[i, :] 
#                     )
#                 else:
#                     self._check_assignment(
#                         player_log.iloc[i, :] 
#                     )        
#             self.assignment = {}
    
#     def _update_assignment(row):
        
        
                
                    
                


        






# s1

In [213]:
import itertools
from tqdm import tqdm

# def find_string_combinations(arr):
#     combinations = list(itertools.combinations(arr, 2))
#     return combinations
def find_string_combinations(arr):
    combinations = list(itertools.permutations(arr, 2))
    return combinations

arr = ["chef_chop", "chef_cook", "chef_plate", 
       "souchef_chop", "souchef_cook", "souchef_plate",
      "server_chop", "server_cook", "server_plate"]

In [14]:
def frequency_dictionary_update(df, spans=3):

    steps = spans - 1

    df = df.join(pd.get_dummies(df["taskId"]))
    df = df.rename(columns={0:"idle_2", 1:"chop", 2:"cook", 3:"plate"})

    df = df.join(pd.get_dummies(df["workerId"]))
    warmup = df[df["round"] <= 2]
    warmup = warmup.rename(columns={0:"idle", 1:"chef", 2:"souchef", 3:"server"})
    start = df[df["round"] >= 3]
#     start = start.rename(columns={0:"idle", 1:"chef", 2:"server", 3:"souchef"})
    start = start.rename(columns={0:"idle", 1:"souchef", 2:"server", 3:"chef"})
    start = start.iloc[:, [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,16,15]]
    df = pd.concat([warmup, start],axis=0)

    df["chef_chop"] = df["chef"] & df["chop"]
    df["chef_cook"] = df["chef"] & df["cook"]
    df["chef_plate"] = df["chef"] & df["plate"]

    df["souchef_chop"] = df["souchef"] & df["chop"]
    df["souchef_cook"] = df["souchef"] & df["cook"]
    df["souchef_plate"] = df["souchef"] & df["plate"]

    df["server_chop"] = df["server"] & df["chop"]
    df["server_cook"] = df["server"] & df["cook"]
    df["server_plate"] = df["server"] & df["plate"]

    arr = ["chef_chop", "chef_cook", "chef_plate", 
           "souchef_chop", "souchef_cook", "souchef_plate",
          "server_chop", "server_cook", "server_plate"]
#     arr = ["chef_chop", "chef_cook", "chef_plate","souchef_chop", "souchef_cook"]
    
    feature_panels = find_string_combinations(arr)

    storage_final = {}
    dat = df.copy()

    for feature_panel in tqdm(feature_panels):
        feature_a = feature_panel[0]
        feature_b = feature_panel[1]
        for i in np.arange(1,7):
            df = df[df["round"] == i]
            feature_panels = find_string_combinations(arr)
            storage = {}
            for responser in df["ResponseId"].unique():
                sub_df = df[df["ResponseId"] == responser]
                for t in np.sort(sub_df["tick"].unique())[:-steps]:
                    if np.sum(sub_df[sub_df["tick"] == t][feature_a]) > 0:
                        window = sub_df[(sub_df["tick"] >= t) & (sub_df["tick"] <= t+steps)]
                        if np.sum(window[feature_b]) > 0:
                            feature = feature_a + "_" + feature_b
                            if not storage.get(feature):
                                storage[feature] = np.array([1])
                            else: 
                                storage[feature] += 1
                                
            for k, v in storage.items():
                storage[k] = np.round(v / len(df["ResponseId"].unique()), 2)
            # update to major
            if not storage_final.get(i):
                storage_final[i] = storage
            else:
                for k, v in storage.items():
                    if not storage_final[i].get(k):
                        storage_final[i][k] = storage[k]
                    else:
                        storage_final[i][k] += storage[k]
            df = dat
    return storage_final

In [15]:
control_frequency = frequency_dictionary_update(control, 6)
s1_frequency = frequency_dictionary_update(s1, 6)
t1_frequency = frequency_dictionary_update(t1, 6)

100%|█████████████████████████████████████████████████████████████████████████████| 72/72 [06:29<00:00,  5.40s/it]
100%|█████████████████████████████████████████████████████████████████████████████| 72/72 [31:40<00:00, 26.39s/it]
100%|█████████████████████████████████████████████████████████████████████████████| 72/72 [42:01<00:00, 35.02s/it]

In [187]:
control_frequency[1]

{'chef_chop_chef_cook': array([1.63]),
 'chef_chop_chef_plate': array([0.03]),
 'chef_chop_souchef_chop': array([1.07]),
 'chef_chop_souchef_cook': array([1.03]),
 'chef_chop_souchef_plate': array([0.36]),
 'chef_chop_server_chop': array([0.89]),
 'chef_chop_server_cook': array([0.47]),
 'chef_chop_server_plate': array([0.48]),
 'chef_cook_chef_chop': array([0.23]),
 'chef_cook_chef_plate': array([0.45]),
 'chef_cook_souchef_chop': array([0.39]),
 'chef_cook_souchef_cook': array([1.29]),
 'chef_cook_souchef_plate': array([0.78]),
 'chef_cook_server_chop': array([0.37]),
 'chef_cook_server_cook': array([0.54]),
 'chef_cook_server_plate': array([2.06]),
 'chef_plate_chef_chop': array([0.03]),
 'chef_plate_chef_cook': array([0.02]),
 'chef_plate_souchef_chop': array([0.11]),
 'chef_plate_souchef_cook': array([0.11]),
 'chef_plate_souchef_plate': array([0.32]),
 'chef_plate_server_chop': array([0.02]),
 'chef_plate_server_cook': array([0.01]),
 'chef_plate_server_plate': array([0.04]),
 'souchef_chop_chef_chop': array([1.1]),
 'souchef_chop_chef_cook': array([1.36]),
 'souchef_chop_chef_plate': array([0.07]),
 'souchef_chop_souchef_cook': array([1.08]),
 'souchef_chop_souchef_plate': array([0.05]),
 'souchef_chop_server_chop': array([0.9]),
 'souchef_chop_server_cook': array([0.47]),
 'souchef_chop_server_plate': array([0.34]),
 'souchef_cook_chef_chop': array([0.07]),
 'souchef_cook_chef_cook': array([0.63]),
 'souchef_cook_chef_plate': array([0.4]),
 'souchef_cook_souchef_chop': array([0.07]),
 'souchef_cook_souchef_plate': array([0.09]),
 'souchef_cook_server_chop': array([0.1]),
 'souchef_cook_server_cook': array([0.5]),
 'souchef_cook_server_plate': array([0.57]),
 'souchef_plate_chef_chop': array([0.72]),
 'souchef_plate_chef_cook': array([0.9]),
 'souchef_plate_chef_plate': array([0.12]),
 'souchef_plate_souchef_chop': array([0.08]),
 'souchef_plate_souchef_cook': array([0.07]),
 'souchef_plate_server_chop': array([0.02]),
 'souchef_plate_server_cook': array([0.02]),
 'souchef_plate_server_plate': array([0.88]),
 'server_chop_chef_chop': array([0.82]),
 'server_chop_chef_cook': array([1.12]),
 'server_chop_chef_plate': array([0.05]),
 'server_chop_souchef_chop': array([0.84]),
 'server_chop_souchef_cook': array([0.89]),
 'server_chop_souchef_plate': array([0.22]),
 'server_chop_server_cook': array([0.46]),
 'server_chop_server_plate': array([0.29]),
 'server_cook_chef_cook': array([0.02]),
 'server_cook_chef_plate': array([0.3]),
 'server_cook_souchef_cook': array([0.07]),
 'server_cook_souchef_plate': array([0.05]),
 'server_cook_server_plate': array([0.05]),
 'server_plate_chef_chop': array([0.44]),
 'server_plate_chef_cook': array([1.37]),
 'server_plate_chef_plate': array([0.07]),
 'server_plate_souchef_chop': array([0.21]),
 'server_plate_souchef_cook': array([0.09]),
 'server_plate_souchef_plate': array([0.7]),
 'server_plate_server_chop': array([0.28])}

In [16]:
s1_frequency[1]

{'chef_chop_chef_cook': array([1.53]),
 'chef_chop_chef_plate': array([0.07]),
 'chef_chop_souchef_chop': array([1.09]),
 'chef_chop_souchef_cook': array([1.1]),
 'chef_chop_souchef_plate': array([0.34]),
 'chef_chop_server_chop': array([0.9]),
 'chef_chop_server_cook': array([0.47]),
 'chef_chop_server_plate': array([0.45]),
 'chef_cook_chef_chop': array([0.25]),
 'chef_cook_chef_plate': array([0.4]),
 'chef_cook_souchef_chop': array([0.49]),
 'chef_cook_souchef_cook': array([1.2]),
 'chef_cook_souchef_plate': array([0.63]),
 'chef_cook_server_chop': array([0.37]),
 'chef_cook_server_cook': array([0.5]),
 'chef_cook_server_plate': array([2.18]),
 'chef_plate_chef_chop': array([0.01]),
 'chef_plate_chef_cook': array([0.01]),
 'chef_plate_souchef_chop': array([0.05]),
 'chef_plate_souchef_cook': array([0.11]),
 'chef_plate_souchef_plate': array([0.29]),
 'chef_plate_server_cook': array([0.]),
 'chef_plate_server_plate': array([0.07]),
 'souchef_chop_chef_chop': array([1.12]),
 'souchef_chop_chef_cook': array([1.47]),
 'souchef_chop_chef_plate': array([0.07]),
 'souchef_chop_souchef_cook': array([1.05]),
 'souchef_chop_souchef_plate': array([0.11]),
 'souchef_chop_server_chop': array([0.9]),
 'souchef_chop_server_cook': array([0.46]),
 'souchef_chop_server_plate': array([0.47]),
 'souchef_cook_chef_chop': array([0.11]),
 'souchef_cook_chef_cook': array([0.72]),
 'souchef_cook_chef_plate': array([0.37]),
 'souchef_cook_souchef_chop': array([0.09]),
 'souchef_cook_souchef_plate': array([0.09]),
 'souchef_cook_server_chop': array([0.1]),
 'souchef_cook_server_cook': array([0.53]),
 'souchef_cook_server_plate': array([0.69]),
 'souchef_plate_chef_chop': array([0.59]),
 'souchef_plate_chef_cook': array([0.73]),
 'souchef_plate_chef_plate': array([0.16]),
 'souchef_plate_souchef_chop': array([0.13]),
 'souchef_plate_souchef_cook': array([0.13]),
 'souchef_plate_server_chop': array([0.02]),
 'souchef_plate_server_cook': array([0.01]),
 'souchef_plate_server_plate': array([0.76]),
 'server_chop_chef_chop': array([0.84]),
 'server_chop_chef_cook': array([1.11]),
 'server_chop_chef_plate': array([0.04]),
 'server_chop_souchef_chop': array([0.85]),
 'server_chop_souchef_cook': array([0.87]),
 'server_chop_souchef_plate': array([0.23]),
 'server_chop_server_cook': array([0.44]),
 'server_chop_server_plate': array([0.25]),
 'server_cook_chef_chop': array([0.]),
 'server_cook_chef_cook': array([0.04]),
 'server_cook_chef_plate': array([0.3]),
 'server_cook_souchef_cook': array([0.06]),
 'server_cook_souchef_plate': array([0.04]),
 'server_cook_server_plate': array([0.07]),
 'server_plate_chef_chop': array([0.39]),
 'server_plate_chef_cook': array([1.32]),
 'server_plate_chef_plate': array([0.11]),
 'server_plate_souchef_chop': array([0.29]),
 'server_plate_souchef_cook': array([0.11]),
 'server_plate_souchef_plate': array([0.59]),
 'server_plate_server_chop': array([0.25])}

In [17]:
# def frequency_dictionary(df, spans=3):
#     worker_id = [1,2,3]
#     tasks_id = [1,2,3]
#     steps = spans - 1

#     df = df.join(pd.get_dummies(df["taskId"]))
#     df = df.rename(columns={0:"idle_2", 1:"chop", 2:"cook", 3:"plate"})

#     df = df.join(pd.get_dummies(df["workerId"]))
#     warmup = df[df["round"] <= 2]
#     warmup = warmup.rename(columns={0:"idle", 1:"chef", 2:"souchef", 3:"server"})
#     start = df[df["round"] >= 3]
#     start = start.rename(columns={0:"idle", 1:"chef", 2:"server", 3:"souchef"})
#     start = start.iloc[:, [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,16,15]]
#     df = pd.concat([warmup, start],axis=0)

#     df["chef_chop"] = df["chef"] & df["chop"]
#     df["chef_cook"] = df["chef"] & df["cook"]
#     df["chef_plate"] = df["chef"] & df["plate"]

#     df["souchef_chop"] = df["souchef"] & df["chop"]
#     df["souchef_cook"] = df["souchef"] & df["cook"]
#     df["souchef_plate"] = df["souchef"] & df["plate"]

#     df["server_chop"] = df["server"] & df["chop"]
#     df["server_cook"] = df["server"] & df["cook"]
#     df["server_plate"] = df["server"] & df["plate"]

#     arr = ["chef_chop", "chef_cook", "chef_plate", 
#            "souchef_chop", "souchef_cook", "souchef_plate",
#           "server_chop", "server_cook", "server_plate", "idle"]

#     storage_final = {}
#     dat = df.copy()
#     for i in tqdm(np.arange(1,7)):
#         df = df[df["round"] == i]
#         feature_panels = find_string_combinations(arr)
#         storage = {}
#         for responser in df["ResponseId"].unique():
#             sub_df = df[df["ResponseId"] == responser]
#             for t in np.sort(sub_df["tick"].unique())[:-steps]:
#                 sub_df = sub_df[(sub_df["tick"] >= t) & (sub_df["tick"] <= t+steps)]
#                 for feature_panel in feature_panels:
#                     feature_a = feature_panel[0]
#                     feature_b = feature_panel[1]
#                     if np.sum(sub_df[feature_a]) > 0 and np.sum(sub_df[feature_b]) > 0:
#                         feature = feature_a + "_" + feature_b
#                         count = min(np.sum(sub_df[feature_a]), np.sum(sub_df[feature_b]))
#                         if not storage.get(feature):
#                             storage[feature] = np.array([count])
#                         else: 
#                             storage[feature] += count
#         for k, v in storage.items():
#             storage[k] = np.round(v / len(df["ResponseId"].unique()), 2)
#         df = dat
#         storage_final[i] = storage
#     return storage_final

In [18]:
# s1_frequency = frequency_dictionary(s1, 6)
# t1_frequency = frequency_dictionary(t1, 6)

In [21]:
def dic_to_df(dic):
    try:
        round1 = pd.DataFrame(dic[1]).T.reset_index()
    except:
        pdb.set_trace()
    round2 = pd.DataFrame(dic[2]).T.rename(columns={0:1}).reset_index()
    df = pd.merge(round1,round2, how='outer')

    round3 = pd.DataFrame(dic[3]).T.rename(columns={0:2}).reset_index()
    df = pd.merge(df,round3, how='outer')

    round4 = pd.DataFrame(dic[4]).T.rename(columns={0:3}).reset_index()
    df = pd.merge(df,round4, how='outer')

    round5 = pd.DataFrame(dic[5]).T.rename(columns={0:4}).reset_index()
    df = pd.merge(df,round5, how='outer')

    round6 = pd.DataFrame(dic[6]).T.rename(columns={0:5}).reset_index()
    df = pd.merge(df,round6, how='outer')

    df = df.fillna(0).rename(columns = {"index":"strategy", 
                                  0:"round 1",
                                  1:"round 2",
                                  2:"round 3",
                                  3:"round 4",
                                  4:"round 5",
                                  5:"round 6"})
    return df

In [66]:
pd.merge(final, dic_to_df(control_frequency), on="strategy")

,strategy,round 1_x,round 2_x,round 3_x,round 4_x,round 5_x,round 6_x,round 1_y,round 2_y,round 3_y,round 4_y,round 5_y,round 6_y,round 1,round 2,round 3,round 4,round 5,round 6
0,chef_chop_chef_cook,1.53,1.50,0.00,0.00,0.00,0.00,1.58,1.51,0.00,0.00,0.00,0.00,1.63,1.58,0.00,0.00,0.00,0.00
1,chef_chop_chef_plate,0.07,0.01,0.00,0.00,0.00,0.00,0.02,0.03,0.00,0.00,0.00,0.00,0.03,0.01,0.00,0.00,0.00,0.00
2,chef_chop_souchef_chop,1.09,1.00,0.00,0.00,0.00,0.00,1.05,0.99,0.00,0.00,0.00,0.00,1.07,1.07,0.00,0.00,0.00,0.00
3,chef_chop_souchef_cook,1.10,0.93,0.00,0.00,0.00,0.00,1.10,0.94,0.00,0.00,0.00,0.00,1.03,0.90,0.00,0.00,0.00,0.00
4,chef_chop_souchef_plate,0.34,0.19,0.00,0.00,0.00,0.00,0.36,0.20,0.00,0.00,0.00,0.00,0.36,0.18,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,server_plate_souchef_plate,0.59,0.66,1.00,0.98,1.00,0.81,0.58,0.59,0.85,0.88,0.78,0.81,0.70,0.72,0.87,0.73,0.75,0.73
66,server_plate_server_chop,0.25,0.40,0.81,1.09,1.01,0.84,0.31,0.41,0.67,0.91,1.05,0.84,0.28,0.42,0.63,0.76,0.67,0.78
67,server_cook_souchef_chop,0.00,0.02,0.11,0.17,0.11,0.12,0.00,0.02,0.25,0.30,0.34,0.38,0.00,0.00,0.05,0.09,0.11,0.10
68,server_cook_server_chop,0.00,0.00,0.05,0.06,0.04,0.03,0.00,0.00,0.07,0.06,0.05,0.07,0.00,0.00,0.02,0.05,0.02,0.02
69,server_plate_server_cook,0.00,0.00,0.11,0.07,0.07,0.07,0.01,0.00,0.20,0.12,0.14,0.15,0.00,0.00,0.13,0.11,0.11,0.08

In [201]:
final = pd.merge(dic_to_df(s1_frequency), dic_to_df(t1_frequency), on="strategy")
final = pd.merge(final, dic_to_df(control_frequency), on="strategy")
s1_final = final.iloc[:, 0:7].rename(columns={
    "round 1_x":"round 1","round 2_x":"round 2","round 3_x":"round 3",
    "round 4_x":"round 4","round 5_x":"round 5","round 6_x":"round 6",
})
t1_final = final.iloc[:, [0,7,8,9,10,11,12]].rename(columns={
    "round 1_y":"round 1","round 2_y":"round 2","round 3_y":"round 3",
    "round 4_y":"round 4","round 5_y":"round 5","round 6_y":"round 6",
})
control_final = final.iloc[:, [0, 13,14,15,16,17,18]].rename(columns={
    "round 1_z":"round 1","round 2_z":"round 2","round 3_z":"round 3",
    "round 4_z":"round 4","round 5_z":"round 5","round 6_z":"round 6",
})
dif = s1_final.iloc[:,1:] - t1_final.iloc[:,1:]
# dif
dif_st = s1_final.iloc[:,1:] - t1_final.iloc[:,1:]
dif_ct = control_final.iloc[:,1:] - t1_final.iloc[:,1:]
dif_cs = control_final.iloc[:,1:] - s1_final.iloc[:,1:]

In [202]:
rows = [10, 15, 29, 36, 38, 45, 51]

In [203]:
dif_st.iloc[rows,:]

    round 1  round 2  round 3  round 4  round 5  round 6
10     0.05    -0.14     0.00     0.00     0.00     0.00
15     0.08    -0.29     0.00     0.00     0.00     0.00
29     0.01     0.03    -0.16    -0.22    -0.49    -0.64
36     0.03     0.03     0.06     0.16     0.23     0.41
38    -0.06    -0.03    -0.17     0.32     0.35     0.28
45     0.00     0.00    -0.06    -0.19    -0.23    -0.25
51    -0.04     0.09     0.07     0.32     0.31     0.31

In [205]:
dif_ct.iloc[rows,:]

    round 1  round 2  round 3  round 4  round 5  round 6
10    -0.05    -0.11     0.00     0.00     0.00     0.00
15    -0.04    -0.24     0.00     0.00     0.00     0.00
29     0.02    -0.03    -0.59    -0.73    -0.91    -0.88
36     0.03    -0.01     0.19     0.60     0.62     0.57
38    -0.18    -0.03    -0.22     0.52     0.55     0.56
45     0.01    -0.01    -0.15    -0.27    -0.29    -0.31
51    -0.02     0.05     0.00     0.14     0.20     0.17

In [206]:
dif_cs.iloc[rows,:]

    round 1  round 2  round 3  round 4  round 5  round 6
10    -0.10     0.03     0.00     0.00     0.00     0.00
15    -0.12     0.05     0.00     0.00     0.00     0.00
29     0.01    -0.06    -0.43    -0.51    -0.42    -0.24
36     0.00    -0.04     0.13     0.44     0.39     0.16
38    -0.12     0.00    -0.05     0.20     0.20     0.28
45     0.01    -0.01    -0.09    -0.08    -0.06    -0.06
51     0.02    -0.04    -0.07    -0.18    -0.11    -0.14

In [88]:
# dif[30:]

In [75]:
s1_final.iloc[rows,:]

,strategy,round 1,round 2,round 3,round 4,round 5,round 6
10,chef_cook_souchef_chop,0.49,0.68,0.00,0.00,0.00,0.00
15,chef_cook_server_plate,2.18,2.93,0.00,0.00,0.00,0.00
29,souchef_chop_server_cook,0.46,0.19,0.75,1.01,0.93,0.89
36,souchef_cook_server_chop,0.10,0.16,1.29,0.97,0.91,0.98
38,souchef_cook_server_plate,0.69,0.81,1.71,1.67,1.62,1.40
45,souchef_plate_server_cook,0.01,0.01,0.12,0.14,0.13,0.12
51,server_chop_souchef_cook,0.87,0.68,1.64,1.71,1.60,1.57

In [83]:
t1_final.iloc[rows,:]

,strategy,round 1,round 2,round 3,round 4,round 5,round 6
10,chef_cook_souchef_chop,0.44,0.82,0.00,0.00,0.00,0.00
15,chef_cook_server_plate,2.10,3.22,0.00,0.00,0.00,0.00
29,souchef_chop_server_cook,0.45,0.16,0.91,1.23,1.42,1.53
36,souchef_cook_server_chop,0.07,0.13,1.23,0.81,0.68,0.57
38,souchef_cook_server_plate,0.75,0.84,1.88,1.35,1.27,1.12
45,souchef_plate_server_cook,0.01,0.01,0.18,0.33,0.36,0.37
51,server_chop_souchef_cook,0.91,0.59,1.57,1.39,1.29,1.26

In [98]:
rows = [10, 15, 29, 36, 38, 45, 51]

In [100]:
control_final.iloc[rows,1:]

    round 1  round 2  round 3  round 4  round 5  round 6
10     0.39     0.71     0.00     0.00     0.00     0.00
15     2.06     2.98     0.00     0.00     0.00     0.00
29     0.47     0.13     0.32     0.50     0.51     0.65
36     0.10     0.12     1.42     1.41     1.30     1.14
38     0.57     0.81     1.66     1.87     1.82     1.68
45     0.02     0.00     0.03     0.06     0.07     0.06
51     0.89     0.64     1.57     1.53     1.49     1.43

In [102]:
dif_cs.iloc[rows,:]

    round 1  round 2  round 3  round 4  round 5  round 6  strategy
10    -0.10     0.03     0.00     0.00     0.00     0.00       NaN
15    -0.12     0.05     0.00     0.00     0.00     0.00       NaN
29     0.01    -0.06    -0.43    -0.51    -0.42    -0.24       NaN
36     0.00    -0.04     0.13     0.44     0.39     0.16       NaN
38    -0.12     0.00    -0.05     0.20     0.20     0.28       NaN
45     0.01    -0.01    -0.09    -0.08    -0.06    -0.06       NaN
51     0.02    -0.04    -0.07    -0.18    -0.11    -0.14       NaN

In [52]:
# dif.iloc[[7,8,4,14,15,16,20],:]
dif.iloc[rows,:]

    round 1  round 2  round 3  round 4  round 5  round 6
10     0.05    -0.14     0.00     0.00     0.00     0.00
15     0.08    -0.29     0.00     0.00     0.00     0.00
29     0.01     0.03    -0.16    -0.22    -0.49    -0.64
36     0.03     0.03     0.06     0.16     0.23     0.41
38    -0.06    -0.03    -0.17     0.32     0.35     0.28
45     0.00     0.00    -0.06    -0.19    -0.23    -0.25
51    -0.04     0.09     0.07     0.32     0.31     0.31
65     0.01     0.07     0.15     0.10     0.22     0.00

In [53]:
dif_ct.iloc[rows,:]

    round 1  round 2  round 3  round 4  round 5  round 6
10    -0.05    -0.11     0.00     0.00     0.00     0.00
15    -0.04    -0.24     0.00     0.00     0.00     0.00
29     0.02    -0.03    -0.59    -0.73    -0.91    -0.88
36     0.03    -0.01     0.19     0.60     0.62     0.57
38    -0.18    -0.03    -0.22     0.52     0.55     0.56
45     0.01    -0.01    -0.15    -0.27    -0.29    -0.31
51    -0.02     0.05     0.00     0.14     0.20     0.17
65     0.12     0.13     0.02    -0.15    -0.03    -0.08

In [70]:
control_final.iloc[rows,:]

,strategy,round 1,round 2,round 3,round 4,round 5,round 6
10,chef_cook_souchef_chop,0.39,0.71,0.00,0.00,0.00,0.00
15,chef_cook_server_plate,2.06,2.98,0.00,0.00,0.00,0.00
29,souchef_chop_server_cook,0.47,0.13,0.32,0.50,0.51,0.65
36,souchef_cook_server_chop,0.10,0.12,1.42,1.41,1.30,1.14
38,souchef_cook_server_plate,0.57,0.81,1.66,1.87,1.82,1.68
45,souchef_plate_server_cook,0.02,0.00,0.03,0.06,0.07,0.06
51,server_chop_souchef_cook,0.89,0.64,1.57,1.53,1.49,1.43
65,server_plate_souchef_plate,0.70,0.72,0.87,0.73,0.75,0.73

In [61]:
# s1_final.iloc[[7,8,4,14,15,16,20],:]
s1_final.iloc[rows,:]

,strategy,round 1,round 2,round 3,round 4,round 5,round 6
10,chef_cook_souchef_chop,0.49,0.68,0.00,0.00,0.00,0.00
15,chef_cook_server_plate,2.18,2.93,0.00,0.00,0.00,0.00
29,souchef_chop_server_cook,0.46,0.19,0.75,1.01,0.93,0.89
36,souchef_cook_server_chop,0.10,0.16,1.29,0.97,0.91,0.98
38,souchef_cook_server_plate,0.69,0.81,1.71,1.67,1.62,1.40
45,souchef_plate_server_cook,0.01,0.01,0.12,0.14,0.13,0.12
51,server_chop_souchef_cook,0.87,0.68,1.64,1.71,1.60,1.57
65,server_plate_souchef_plate,0.59,0.66,1.00,0.98,1.00,0.81

In [72]:
# t1_final.iloc[[7,8,4,14,15,16,20],:]
t1_final.iloc[rows,:]

,strategy,round 1,round 2,round 3,round 4,round 5,round 6
10,chef_cook_souchef_chop,0.44,0.82,0.00,0.00,0.00,0.00
11,chef_cook_souchef_cook,1.16,1.09,0.00,0.00,0.00,0.00
15,chef_cook_server_plate,2.10,3.22,0.00,0.00,0.00,0.00
29,souchef_chop_server_cook,0.45,0.16,0.91,1.23,1.42,1.53
36,souchef_cook_server_chop,0.07,0.13,1.23,0.81,0.68,0.57
38,souchef_cook_server_plate,0.75,0.84,1.88,1.35,1.27,1.12
45,souchef_plate_server_cook,0.01,0.01,0.18,0.33,0.36,0.37
51,server_chop_souchef_cook,0.91,0.59,1.57,1.39,1.29,1.26
65,server_plate_souchef_cook,0.13,0.18,1.51,1.13,0.99,0.90
68,server_cook_souchef_chop,0.00,0.02,0.25,0.30,0.34,0.38

In [ ]:
for featureA_featureB, find when featureA is taken place (t1, t2, ... tn), for each t_i in (t_1 ... t_n), check if featureB exists within the window (t_i, t_i+5). Sum all players and all corresponding boolen value (0 or 1), and divide by the number of players.